Jupyter Notebook を起動し、新しいノートブックを作成せよ。

In [1]:
import numpy as np

1 行のセルに print("Hello, Data Science!") を書いて実行。

In [2]:
print("Hello, Data Science!")

Hello, Data Science!


Markdown セルを追加し、# 私の最初のノート と見出しを書く。

len? を実行してヘルプを表示。

In [3]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

np.mean?? でソースコードを確認。

In [4]:
np.mean??

Signature:      
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.mean(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function mean at 0x000002AED1D07CE0>
File:            c:\python\python-data-science-handbook\venv\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_mean_dispatcher)
def mean(a, axis=None, dtype=None, out=None, keepdims=np._NoValue, *,
         where=np._NoValue):
    """
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : 

Tab 補完で numpy.random.default_rng を補完。

In [5]:
np.random.default_rng

<cyfunction default_rng at 0x000002AED1F716C0>

%lsmagic で Magic コマンド一覧を表示。

In [6]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %code_wrap  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %mamba  %matplotlib  %micromamba  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %uv  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%code_wrap  %%debug  %%file  %%html  %%javascript  %%js  %%l

%timeit sum(range(1_000)) を計測。

In [7]:
%timeit sum(range(1_000))

10.3 μs ± 95 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


%run hello.py で自作スクリプトを実行。

In [9]:
%run hello.py 

%prun で自作関数のプロファイルを取得。

In [11]:
def sample_func_1():
    index_list = []
    for i in range(1000000):
        index_list.append(i)


def sample_func_2():
    index_list = []
    for i in range(2000000):
        index_list.append(i)


def sample_func_3():
    index_list = []
    for i in range(6000000):
        index_list.append(i)


def sample_func_4():
    sample_func_1()
    sample_func_2()
    sample_func_3()


In [12]:
%%prun
sample_func_4()

         9000187 function calls (9000185 primitive calls) in 2.060 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  9000000    0.876    0.000    0.876    0.000 {method 'append' of 'list' objects}
        1    0.703    0.703    1.289    1.289 2123655570.py:13(sample_func_3)
        1    0.234    0.234    0.429    0.429 2123655570.py:7(sample_func_2)
        1    0.111    0.111    1.992    1.992 {built-in method builtins.exec}
        1    0.066    0.066    1.881    1.881 2123655570.py:19(sample_func_4)
        1    0.052    0.052    0.097    0.097 2123655570.py:1(sample_func_1)
        2    0.017    0.008    0.031    0.015 {method '__exit__' of 'sqlite3.Connection' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        2    0.000    0.000    0.000    0.000 attrsettr.py:66(_get_attr_opt)
        1    0.000    0.000    0.000    0.000 socket.py:771(recv_multipart)
      

Python リスト [1,2,3] を作り type() を確認。

In [14]:
A=[1,2,3]
type(A)

list

同じ要素で np.array を作り型を比較。

In [15]:
B=np.array(A)
type(B)

numpy.ndarray

arr = np.arange(10) の shape, dtype, ndim を表示。

In [17]:
arr=np.arange(10)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,)
int64
1


14. `np.zeros((10,10))` を生成。


In [18]:
z=np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

arr.reshape(2,5) で形状変更。

In [22]:
arr_reshape=arr.reshape(2,5)
arr_reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

np.linspace(0,1,5) を生成。

In [ ]:
np.linspace?

In [25]:
B=np.linspace(0,1,5)
B

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

for ループで 1‒1e7 合計を計測。

In [28]:
%%timeit

c=0
for i in range(1,10**7+1):
    c+=i
c

307 ms ± 3.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


同じ計算を np.sum で行い速度比較。

In [32]:
%%timeit
npsum=np.sum(np.arange(1,10**7+1))
npsum

26.5 ms ± 734 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


dtype='float32' の乱数 100 万個を生成。

In [33]:
import random

In [43]:
%%timeit
for _ in range(1000000):
    random.random()

type(random.random())

37.5 ms ± 681 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


dtype='float32' の乱数 100 万個を生成。

In [54]:
np.random.rand(1000000).astype(np.float32)

array([0.5046811 , 0.9345454 , 0.33262816, ..., 0.38014734, 0.15653077,
       0.34811625], shape=(1000000,), dtype=float32)

コピーとビューの挙動を確認。

In [55]:
# 元の配列
original_array = np.array([1, 2, 3, 4, 5])
print("元の配列:", original_array)

# コピーを作成
copied_array = original_array.copy()
print("コピーされた配列:", copied_array)

# コピーを変更
copied_array[0] = 99
print("コピーを変更後:", copied_array)
print("元の配列 (変化なし):", original_array)


元の配列: [1 2 3 4 5]
コピーされた配列: [1 2 3 4 5]
コピーを変更後: [99  2  3  4  5]
元の配列 (変化なし): [1 2 3 4 5]


In [56]:
zeroto99=np.arange(100)
zeroto99[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
random_matrix = np.random.rand(10, 10)
random_matrix

array([[0.36299215, 0.14113208, 0.1675409 , 0.07018762, 0.23225158,
        0.37938882, 0.79561016, 0.80391638, 0.85289187, 0.58404721],
       [0.78450903, 0.54580706, 0.01214294, 0.00359842, 0.03141421,
        0.25305525, 0.27037982, 0.29719836, 0.30239593, 0.24460734],
       [0.96692448, 0.88661685, 0.27248427, 0.31776818, 0.11701264,
        0.45632456, 0.08454866, 0.99405197, 0.16624555, 0.81318747],
       [0.41748381, 0.18421164, 0.30628649, 0.86819575, 0.26715028,
        0.38414402, 0.50117447, 0.96958957, 0.93492302, 0.21405413],
       [0.04384182, 0.6006158 , 0.07222526, 0.91271444, 0.63165852,
        0.16171922, 0.11532212, 0.67036596, 0.36277024, 0.64103941],
       [0.12524127, 0.29265946, 0.72903712, 0.21832846, 0.30810774,
        0.64315293, 0.93769788, 0.90444555, 0.23245298, 0.61836503],
       [0.14556648, 0.91895951, 0.89256575, 0.65154766, 0.79878613,
        0.0870503 , 0.62490813, 0.13657838, 0.85951824, 0.13245221],
       [0.75017235, 0.6550988 , 0.0488185

10×10 配列の 1 行目を取得。

In [60]:
random_matrix[0]

array([0.94808679, 0.02449398, 0.21758012, 0.50272685, 0.2501649 ,
       0.37924143, 0.98888533, 0.58935063, 0.64729083, 0.19324155])

同配列の 1 列目を取得。

In [61]:
random_matrix[:,0]

array([0.94808679, 0.11536561, 0.17601435, 0.85054828, 0.30448198,
       0.08530256, 0.77704469, 0.15672408, 0.90463877, 0.33797877])

3×3 のサブ配列をスライス取得。

In [62]:
random_matrix[:3,:3]

array([[0.94808679, 0.02449398, 0.21758012],
       [0.11536561, 0.5586268 , 0.18507408],
       [0.17601435, 0.98544903, 0.71855757]])

ビューを変更して元配列も変わることを確認。

In [64]:
c=random_matrix
c[0,0]=0
random_matrix[0]

array([0.        , 0.02449398, 0.21758012, 0.50272685, 0.2501649 ,
       0.37924143, 0.98888533, 0.58935063, 0.64729083, 0.19324155])

(2,3) 要素を書き換え。

In [70]:
c[2,2]=0
c[:3,:3]

array([[0.        , 0.02449398, 0.21758012],
       [0.11536561, 0.5586268 , 0.18507408],
       [0.17601435, 0.98544903, 0.        ]])

arr[::-1] で逆順。

In [109]:
original=np.array([
     [1,2,3,4,5,6,7,8,9,10],
     [11,12,13,14,15,16,17,18,19,20],
     [21,22,23,24,25,26,27,28,29,30],
     [31,32,33,34,35,36,37,38,39,40]
     ])

In [110]:
arr=original.copy()

In [111]:
arr[::-1]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

arr[:,::2] で偶数列抽出。

In [98]:

arr[:,::2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

3 の倍数だけ抽出。

In [99]:
arr[arr%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 33, 36, 39])

奇数を ‑1 に置換。

In [106]:
arr[arr%2!=0]=-1
arr

array([[-1,  2, -1,  4, -1,  6, -1,  8, -1, 10],
       [-1, 12, -1, 14, -1, 16, -1, 18, -1, 20],
       [-1, 22, -1, 24, -1, 26, -1, 28, -1, 40],
       [-1, 32, -1, 34, -1, 36, -1, 38, -1, 40]])

In [133]:
original

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

np.square(arr) を計算。

In [112]:
np.square(original)

array([[   1,    4,    9,   16,   25,   36,   49,   64,   81,  100],
       [ 121,  144,  169,  196,  225,  256,  289,  324,  361,  400],
       [ 441,  484,  529,  576,  625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600]])

np.sin, np.cos, np.tan を一括計算。

In [115]:
theta=np.pi*(45/180)
theta
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

0.7071067811865476
0.7071067811865476
0.9999999999999999


np.square(arr) を計算。

In [119]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03, 2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
        7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
        3.93133430e+12, 1.06864746e+13],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14, 5.83461743e+14,
        1.58601345e+15, 4.31123155e+15, 1.17191424e+16, 3.18559318e+16,
        8.65934004e+16, 2.35385267e+17]])

乱数 100 万個の平均を計算。

In [124]:
n=1000000
a=np.random.rand(n)

In [125]:
a.sum()/n

np.float64(0.5001624570871291)

最大値と最小値の差を求める。

In [126]:
min_a=min(a)
max_a=max(a)
max_a-min_a

np.float64(0.9999991804720388)

 次元配列で axis=0 合計。

In [132]:
sum_axis_0 = np.sum(original, axis=0)
sum_axis_0

array([ 64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

np.percentile で 25/50/75 % 点。

In [143]:
for i in [0,25,50,75,100]:
    print(np.percentile(original,i))

1.0
10.75
20.5
30.25
40.0


argsort で昇順インデックス。

In [144]:
np.argsort(original)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

partition で上位 5 要素抽出。

In [161]:
p=np.partition(sum_axis_0,kth=5)
print(p)
p[:5]


[ 64  68  72  76  80  84  88  92  96 100]


array([64, 68, 72, 76, 80])

rng = np.random.default_rng(0) で再現可能に。

In [13]:
print("--- Run 1 ---")
rng1 = np.random.default_rng(0) # Seeded with 0
print("Random integers (rng1):", rng1.integers(10, size=5))
print("Random floats (rng1):", rng1.random(size=3))

print("\n--- Run 2 (Same Seed) ---")
rng2 = np.random.default_rng(0) # Seeded with 0 again
print("Random integers (rng2):", rng2.integers(10, size=5))
print("Random floats (rng2):", rng2.random(size=3))

--- Run 1 ---
Random integers (rng1): [8 6 5 2 3]
Random floats (rng1): [0.01652764 0.81327024 0.91275558]

--- Run 2 (Same Seed) ---
Random integers (rng2): [8 6 5 2 3]
Random floats (rng2): [0.01652764 0.81327024 0.91275558]


In [14]:
rng1 = np.random.default_rng(0)
random_matrix2 = rng1.integers(10, size=(5,5))
random_matrix2

array([[8, 6, 5, 2, 3],
       [0, 0, 0, 1, 8],
       [6, 9, 5, 6, 9],
       [7, 6, 5, 5, 9],
       [2, 8, 6, 0, 3]])

5×5 配列に [0,1,2,3,4] を足す。

In [15]:
random_matrix2+np.array([0,1,2,3,4])

array([[ 8,  7,  7,  5,  7],
       [ 0,  1,  2,  4, 12],
       [ 6, 10,  7,  9, 13],
       [ 7,  7,  7,  8, 13],
       [ 2,  9,  8,  3,  7]])

列方向に平均 0 のセンタリング。

In [16]:
column_means=random_matrix2.mean(axis=0)
centered=random_matrix2-column_means
centered

array([[ 3.4,  0.2,  0.8, -0.8, -3.4],
       [-4.6, -5.8, -4.2, -1.8,  1.6],
       [ 1.4,  3.2,  0.8,  3.2,  2.6],
       [ 2.4,  0.2,  0.8,  2.2,  2.6],
       [-2.6,  2.2,  1.8, -2.8, -3.4]])

In [17]:
centered.mean(axis=0)

array([ 3.55271368e-16,  1.77635684e-16, -1.77635684e-16,  1.77635684e-16,
       -3.55271368e-16])

メッシュグリッドで z = sin(x)+cos(y)。

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D # 3Dプロットに必要

# 1. x, yの範囲を定義
# -2π から 2π までを100分割した配列を生成
x = np.linspace(-2 * np.pi, 2 * np.pi, 100)
y = np.linspace(-2 * np.pi, 2 * np.pi, 100)

# 2. メッシュグリッドを生成
# xとyの1次元配列から、2次元の座標グリッドX, Yを生成
X, Y = np.meshgrid(x, y)

# 3. zの値を計算
# 各(X, Y)座標に対して Z = sin(X) + cos(Y) を計算
Z = np.sin(X) + np.cos(Y)

# 4. 3Dプロットの準備
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# 5. 3D曲面プロットを実行
# cmapでカラーマップを指定すると見やすくなる
surf = ax.plot_surface(X, Y, Z, cmap='viridis')

# 軸ラベルとタイトルの設定
ax.set_xlabel('x axis')
ax.set_ylabel('y axis')
ax.set_zlabel('z axis')
ax.set_title('z = sin(x) + cos(y)')

# カラーバーを追加
fig.colorbar(surf, shrink=0.5, aspect=10)

# グラフを表示
plt.show()


ブロードキャストで距離行列を生成。

In [36]:
np.newaxis?

Type:        NoneType
String form: None
Docstring:   The type of the None singleton.

In [24]:
X = np.array([[0, 0], [1, 2], [3, 3], [5, 2], [3, 0]])
sum_sq = np.sum(X**2, axis=1)
dist_sq = sum_sq[:, np.newaxis] + sum_sq[np.newaxis, :] - 2 * (X @ X.T)
dist_sq_clipped = np.maximum(dist_sq, 0)
dist_matrix_fast = np.sqrt(dist_sq_clipped)
print("方法2で生成した距離行列:")
print(dist_matrix_fast)

方法2で生成した距離行列:
[[0.         2.23606798 4.24264069 5.38516481 3.        ]
 [2.23606798 0.         2.23606798 4.         2.82842712]
 [4.24264069 2.23606798 0.         2.23606798 3.        ]
 [5.38516481 4.         2.23606798 0.         2.82842712]
 [3.         2.82842712 3.         2.82842712 0.        ]]


In [30]:
A=np.array([[1],[2],[3]])
B=np.array([[1,2,3,4]])
A+B

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [31]:
A=np.array([[1],[2],[3]])
B=np.array([[1,2],[3,4]])
A+B

ValueError: operands could not be broadcast together with shapes (3,1) (2,2) 

In [2]:
H,W=3,3
rgb_image = np.random.randint(0, 256, size=(H, W, 3), dtype=np.uint8)

color_fix=[10,20,30]
fixed_image=rgb_image+color_fix
print(rgb_image)
fixed_image

[[[177 111  77]
  [245  44  12]
  [ 52 179  70]]

 [[242  14  80]
  [ 36 191  39]
  [152  53 250]]

 [[156 221 186]
  [146 144  65]
  [ 21  26  91]]]


array([[[187, 131, 107],
        [255,  64,  42],
        [ 62, 199, 100]],

       [[252,  34, 110],
        [ 46, 211,  69],
        [162,  73, 280]],

       [[166, 241, 216],
        [156, 164,  95],
        [ 31,  46, 121]]])

In [12]:
import numpy as np
rng=np.random.default_rng(0)
rndX=rng.integers(10, size=(10,10))
rndX

array([[8, 6, 5, 2, 3, 0, 0, 0, 1, 8],
       [6, 9, 5, 6, 9, 7, 6, 5, 5, 9],
       [2, 8, 6, 0, 3, 8, 5, 0, 7, 7],
       [8, 1, 0, 8, 0, 5, 0, 2, 4, 4],
       [4, 0, 0, 1, 0, 6, 5, 6, 2, 6],
       [7, 3, 4, 9, 8, 9, 3, 6, 9, 6],
       [8, 6, 7, 3, 8, 1, 5, 7, 8, 5],
       [3, 3, 4, 4, 7, 8, 0, 9, 5, 3],
       [6, 5, 2, 3, 7, 5, 5, 3, 7, 3],
       [3, 8, 2, 2, 7, 6, 0, 0, 3, 8]])

In [14]:
avg_X=rndX.mean(axis=1)
avg_X

array([3.3, 6.7, 4.6, 3.2, 3. , 6.4, 5.8, 4.6, 4.6, 3.9])

In [15]:
mean_X=rndX-avg_X

In [16]:
norm_X=np.linalg.norm(mean_X,ord=2,axis=0)
norm_X

array([ 9.84377976, 10.83051245,  8.03741252,  9.1214034 , 12.32882801,
        9.3059121 , 12.04159458, 10.09950494,  8.08702665,  8.99444273])

In [17]:
X_normalized=mean_X/norm_X
X_normalized

array([[ 0.47745887, -0.06463221,  0.04976726, -0.1315587 ,  0.        ,
        -0.68773484, -0.48166378, -0.45546787, -0.44515743,  0.45583702],
       [ 0.27428489,  0.21236299,  0.04976726,  0.30697031,  0.48666426,
         0.06447514,  0.0166091 ,  0.0396059 ,  0.04946194,  0.56701679],
       [-0.13206309,  0.12003125,  0.17418541, -0.35082321,  0.        ,
         0.17193371, -0.06643638, -0.45546787,  0.29677162,  0.34465726],
       [ 0.47745887, -0.52629089, -0.57232349,  0.52623481, -0.24333213,
        -0.150442  , -0.48166378, -0.25743836, -0.07419291,  0.01111798],
       [ 0.0711109 , -0.61862262, -0.57232349, -0.24119096, -0.24333213,
        -0.04298343, -0.06643638,  0.13862066, -0.32150259,  0.2334775 ],
       [ 0.37587188, -0.34162742, -0.07465089,  0.63586706,  0.40555355,
         0.27939228, -0.23252734,  0.13862066,  0.5440813 ,  0.2334775 ],
       [ 0.47745887, -0.06463221,  0.29860356, -0.02192645,  0.40555355,
        -0.58027627, -0.06643638,  0.23763541