Jupyter Notebook を起動し、新しいノートブックを作成せよ。

In [2]:
import numpy as np

1 行のセルに print("Hello, Data Science!") を書いて実行。

In [3]:
print("Hello, Data Science!")

Hello, Data Science!


Markdown セルを追加し、# 私の最初のノート と見出しを書く。

len? を実行してヘルプを表示。

In [4]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

np.mean?? でソースコードを確認。

In [5]:
np.mean??

Signature:      
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.mean(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function mean at 0x000001F93EA35C60>
File:            c:\python\python-data-science-handbook\venv\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_mean_dispatcher)
def mean(a, axis=None, dtype=None, out=None, keepdims=np._NoValue, *,
         where=np._NoValue):
    """
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : 

Tab 補完で numpy.random.default_rng を補完。

In [6]:
np.random.default_rng

<cyfunction default_rng at 0x000001F93EC2C880>

%lsmagic で Magic コマンド一覧を表示。

In [7]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %code_wrap  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %mamba  %matplotlib  %micromamba  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %uv  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%code_wrap  %%debug  %%file  %%html  %%javascript  %%js  %%l

%timeit sum(range(1_000)) を計測。

In [8]:
%timeit sum(range(1_000))

10.4 μs ± 78.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


%run hello.py で自作スクリプトを実行。

In [9]:
%run hello.py 

Hello world.


%prun で自作関数のプロファイルを取得。

In [10]:
def sample_func_1():
    index_list = []
    for i in range(1000000):
        index_list.append(i)


def sample_func_2():
    index_list = []
    for i in range(2000000):
        index_list.append(i)


def sample_func_3():
    index_list = []
    for i in range(6000000):
        index_list.append(i)


def sample_func_4():
    sample_func_1()
    sample_func_2()
    sample_func_3()


In [11]:
%%prun
sample_func_4()

         9000154 function calls (9000152 primitive calls) in 2.056 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  9000000    0.950    0.000    0.950    0.000 {method 'append' of 'list' objects}
        1    0.692    0.692    1.323    1.323 2123655570.py:13(sample_func_3)
        1    0.233    0.233    0.448    0.448 2123655570.py:7(sample_func_2)
        1    0.083    0.083    0.158    0.158 2123655570.py:1(sample_func_1)
        1    0.072    0.072    2.001    2.001 2123655570.py:19(sample_func_4)
        2    0.017    0.008    0.031    0.015 {method '__exit__' of 'sqlite3.Connection' objects}
        2    0.008    0.004    0.016    0.008 socket.py:623(send)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 attrsettr.py:66(_get_attr_opt)
        2    0.000    0.000    0.000    0.000 enum.py:1596(__or__)
       12    0.000    0.000

Python リスト [1,2,3] を作り type() を確認。

In [12]:
A=[1,2,3]
type(A)

list

同じ要素で np.array を作り型を比較。

In [13]:
B=np.array(A)
type(B)

numpy.ndarray

arr = np.arange(10) の shape, dtype, ndim を表示。

In [14]:
arr=np.arange(10)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,)
int64
1


14. `np.zeros((10,10))` を生成。


In [15]:
z=np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

arr.reshape(2,5) で形状変更。

In [16]:
arr_reshape=arr.reshape(2,5)
arr_reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

np.linspace(0,1,5) を生成。

In [17]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000001F93EA6CD60>
File:            c:\python\python-data-science-handbook\venv\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoin

In [18]:
B=np.linspace(0,1,5)
B

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

for ループで 1‒1e7 合計を計測。

In [19]:
%%timeit

c=0
for i in range(1,10**7+1):
    c+=i
c

339 ms ± 11.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


同じ計算を np.sum で行い速度比較。

In [20]:
%%timeit
npsum=np.sum(np.arange(1,10**7+1))
npsum

27.9 ms ± 727 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


dtype='float32' の乱数 100 万個を生成。

In [21]:
import random

In [22]:
%%timeit
for _ in range(1000000):
    random.random()

type(random.random())

39.8 ms ± 413 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


dtype='float32' の乱数 100 万個を生成。

In [23]:
np.random.rand(1000000).astype(np.float32)

array([0.43010008, 0.4456753 , 0.41508624, ..., 0.8703269 , 0.51106006,
       0.6844301 ], shape=(1000000,), dtype=float32)

コピーとビューの挙動を確認。

In [24]:
# 元の配列
original_array = np.array([1, 2, 3, 4, 5])
print("元の配列:", original_array)

# コピーを作成
copied_array = original_array.copy()
print("コピーされた配列:", copied_array)

# コピーを変更
copied_array[0] = 99
print("コピーを変更後:", copied_array)
print("元の配列 (変化なし):", original_array)


元の配列: [1 2 3 4 5]
コピーされた配列: [1 2 3 4 5]
コピーを変更後: [99  2  3  4  5]
元の配列 (変化なし): [1 2 3 4 5]


In [25]:
zeroto99=np.arange(100)
zeroto99[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
random_matrix = np.random.rand(10, 10)
random_matrix

array([[0.01717327, 0.76987266, 0.63694123, 0.42425622, 0.91767668,
        0.32374525, 0.31045288, 0.49433119, 0.85771972, 0.45774097],
       [0.94226477, 0.89924781, 0.29080677, 0.48786333, 0.88704418,
        0.80424755, 0.51141256, 0.85831525, 0.20619179, 0.7984684 ],
       [0.87433731, 0.71543793, 0.21377467, 0.01591723, 0.77369845,
        0.59763444, 0.30376225, 0.67606836, 0.12977526, 0.92390033],
       [0.02267081, 0.32408717, 0.96466836, 0.84784276, 0.94267862,
        0.90315864, 0.42734185, 0.63520824, 0.85179836, 0.54620934],
       [0.42319346, 0.70719051, 0.8409794 , 0.61374556, 0.97763739,
        0.31243262, 0.59668228, 0.37599541, 0.09089385, 0.38620143],
       [0.00613311, 0.68300733, 0.06595848, 0.72537083, 0.81608939,
        0.525334  , 0.90840583, 0.81659204, 0.89340825, 0.95867053],
       [0.79614927, 0.62937386, 0.10602797, 0.42893906, 0.07085921,
        0.06617193, 0.63647392, 0.9186563 , 0.95026733, 0.27959644],
       [0.78918204, 0.3681038 , 0.1382371

10×10 配列の 1 行目を取得。

In [27]:
random_matrix[0]

array([0.01717327, 0.76987266, 0.63694123, 0.42425622, 0.91767668,
       0.32374525, 0.31045288, 0.49433119, 0.85771972, 0.45774097])

同配列の 1 列目を取得。

In [28]:
random_matrix[:,0]

array([0.01717327, 0.94226477, 0.87433731, 0.02267081, 0.42319346,
       0.00613311, 0.79614927, 0.78918204, 0.39229533, 0.95559305])

3×3 のサブ配列をスライス取得。

In [29]:
random_matrix[:3,:3]

array([[0.01717327, 0.76987266, 0.63694123],
       [0.94226477, 0.89924781, 0.29080677],
       [0.87433731, 0.71543793, 0.21377467]])

ビューを変更して元配列も変わることを確認。

In [30]:
c=random_matrix
c[0,0]=0
random_matrix[0]

array([0.        , 0.76987266, 0.63694123, 0.42425622, 0.91767668,
       0.32374525, 0.31045288, 0.49433119, 0.85771972, 0.45774097])

(2,3) 要素を書き換え。

In [31]:
c[2,2]=0
c[:3,:3]

array([[0.        , 0.76987266, 0.63694123],
       [0.94226477, 0.89924781, 0.29080677],
       [0.87433731, 0.71543793, 0.        ]])

arr[::-1] で逆順。

In [32]:
original=np.array([
     [1,2,3,4,5,6,7,8,9,10],
     [11,12,13,14,15,16,17,18,19,20],
     [21,22,23,24,25,26,27,28,29,30],
     [31,32,33,34,35,36,37,38,39,40]
     ])

In [33]:
arr=original.copy()

In [34]:
arr[::-1]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

arr[:,::2] で偶数列抽出。

In [35]:

arr[:,::2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

3 の倍数だけ抽出。

In [36]:
arr[arr%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

奇数を ‑1 に置換。

In [37]:
arr[arr%2!=0]=-1
arr

array([[-1,  2, -1,  4, -1,  6, -1,  8, -1, 10],
       [-1, 12, -1, 14, -1, 16, -1, 18, -1, 20],
       [-1, 22, -1, 24, -1, 26, -1, 28, -1, 30],
       [-1, 32, -1, 34, -1, 36, -1, 38, -1, 40]])

In [38]:
original

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

np.square(arr) を計算。

In [39]:
np.square(original)

array([[   1,    4,    9,   16,   25,   36,   49,   64,   81,  100],
       [ 121,  144,  169,  196,  225,  256,  289,  324,  361,  400],
       [ 441,  484,  529,  576,  625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600]])

np.sin, np.cos, np.tan を一括計算。

In [40]:
theta=np.pi*(45/180)
theta
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

0.7071067811865476
0.7071067811865476
0.9999999999999999


np.square(arr) を計算。

In [41]:
np.exp(arr)

array([[3.67879441e-01, 7.38905610e+00, 3.67879441e-01, 5.45981500e+01,
        3.67879441e-01, 4.03428793e+02, 3.67879441e-01, 2.98095799e+03,
        3.67879441e-01, 2.20264658e+04],
       [3.67879441e-01, 1.62754791e+05, 3.67879441e-01, 1.20260428e+06,
        3.67879441e-01, 8.88611052e+06, 3.67879441e-01, 6.56599691e+07,
        3.67879441e-01, 4.85165195e+08],
       [3.67879441e-01, 3.58491285e+09, 3.67879441e-01, 2.64891221e+10,
        3.67879441e-01, 1.95729609e+11, 3.67879441e-01, 1.44625706e+12,
        3.67879441e-01, 1.06864746e+13],
       [3.67879441e-01, 7.89629602e+13, 3.67879441e-01, 5.83461743e+14,
        3.67879441e-01, 4.31123155e+15, 3.67879441e-01, 3.18559318e+16,
        3.67879441e-01, 2.35385267e+17]])

乱数 100 万個の平均を計算。

In [42]:
n=1000000
a=np.random.rand(n)

In [43]:
a.sum()/n

np.float64(0.5000421691750173)

最大値と最小値の差を求める。

In [44]:
min_a=min(a)
max_a=max(a)
max_a-min_a

np.float64(0.9999967204348055)

 次元配列で axis=0 合計。

In [45]:
sum_axis_0 = np.sum(original, axis=0)
sum_axis_0

array([ 64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

np.percentile で 25/50/75 % 点。

In [46]:
for i in [0,25,50,75,100]:
    print(np.percentile(original,i))

1.0
10.75
20.5
30.25
40.0


argsort で昇順インデックス。

In [47]:
np.argsort(original)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

partition で上位 5 要素抽出。

In [48]:
p=np.partition(sum_axis_0,kth=5)
print(p)
p[:5]


[ 64  68  72  76  80  84  88  92  96 100]


array([64, 68, 72, 76, 80])

rng = np.random.default_rng(0) で再現可能に。

In [49]:
print("--- Run 1 ---")
rng1 = np.random.default_rng(0) # Seeded with 0
print("Random integers (rng1):", rng1.integers(10, size=5))
print("Random floats (rng1):", rng1.random(size=3))

print("\n--- Run 2 (Same Seed) ---")
rng2 = np.random.default_rng(0) # Seeded with 0 again
print("Random integers (rng2):", rng2.integers(10, size=5))
print("Random floats (rng2):", rng2.random(size=3))

--- Run 1 ---
Random integers (rng1): [8 6 5 2 3]
Random floats (rng1): [0.01652764 0.81327024 0.91275558]

--- Run 2 (Same Seed) ---
Random integers (rng2): [8 6 5 2 3]
Random floats (rng2): [0.01652764 0.81327024 0.91275558]


In [50]:
rng1 = np.random.default_rng(0)
random_matrix2 = rng1.integers(10, size=(5,5))
random_matrix2

array([[8, 6, 5, 2, 3],
       [0, 0, 0, 1, 8],
       [6, 9, 5, 6, 9],
       [7, 6, 5, 5, 9],
       [2, 8, 6, 0, 3]])

5×5 配列に [0,1,2,3,4] を足す。

In [51]:
random_matrix2+np.array([0,1,2,3,4])

array([[ 8,  7,  7,  5,  7],
       [ 0,  1,  2,  4, 12],
       [ 6, 10,  7,  9, 13],
       [ 7,  7,  7,  8, 13],
       [ 2,  9,  8,  3,  7]])

列方向に平均 0 のセンタリング。

In [52]:
column_means=random_matrix2.mean(axis=0)
centered=random_matrix2-column_means
centered

array([[ 3.4,  0.2,  0.8, -0.8, -3.4],
       [-4.6, -5.8, -4.2, -1.8,  1.6],
       [ 1.4,  3.2,  0.8,  3.2,  2.6],
       [ 2.4,  0.2,  0.8,  2.2,  2.6],
       [-2.6,  2.2,  1.8, -2.8, -3.4]])

In [53]:
centered.mean(axis=0)

array([ 3.55271368e-16,  1.77635684e-16, -1.77635684e-16,  1.77635684e-16,
       -3.55271368e-16])

メッシュグリッドで z = sin(x)+cos(y)。

In [54]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D # 3Dプロットに必要

# 1. x, yの範囲を定義
# -2π から 2π までを100分割した配列を生成
x = np.linspace(-2 * np.pi, 2 * np.pi, 100)
y = np.linspace(-2 * np.pi, 2 * np.pi, 100)

# 2. メッシュグリッドを生成
# xとyの1次元配列から、2次元の座標グリッドX, Yを生成
X, Y = np.meshgrid(x, y)

# 3. zの値を計算
# 各(X, Y)座標に対して Z = sin(X) + cos(Y) を計算
Z = np.sin(X) + np.cos(Y)

# 4. 3Dプロットの準備
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# 5. 3D曲面プロットを実行
# cmapでカラーマップを指定すると見やすくなる
surf = ax.plot_surface(X, Y, Z, cmap='viridis')

# 軸ラベルとタイトルの設定
ax.set_xlabel('x axis')
ax.set_ylabel('y axis')
ax.set_zlabel('z axis')
ax.set_title('z = sin(x) + cos(y)')

# カラーバーを追加
fig.colorbar(surf, shrink=0.5, aspect=10)

# グラフを表示
plt.show()


ModuleNotFoundError: No module named 'matplotlib'

ブロードキャストで距離行列を生成。

In [ ]:
np.newaxis?

Type:        NoneType
String form: None
Docstring:   The type of the None singleton.

In [ ]:
X = np.array([[0, 0], [1, 2], [3, 3], [5, 2], [3, 0]])
sum_sq = np.sum(X**2, axis=1)
dist_sq = sum_sq[:, np.newaxis] + sum_sq[np.newaxis, :] - 2 * (X @ X.T)
dist_sq_clipped = np.maximum(dist_sq, 0)
dist_matrix_fast = np.sqrt(dist_sq_clipped)
print("方法2で生成した距離行列:")
print(dist_matrix_fast)

方法2で生成した距離行列:
[[0.         2.23606798 4.24264069 5.38516481 3.        ]
 [2.23606798 0.         2.23606798 4.         2.82842712]
 [4.24264069 2.23606798 0.         2.23606798 3.        ]
 [5.38516481 4.         2.23606798 0.         2.82842712]
 [3.         2.82842712 3.         2.82842712 0.        ]]


In [ ]:
A=np.array([[1],[2],[3]])
B=np.array([[1,2,3,4]])
A+B

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [ ]:
A=np.array([[1],[2],[3]])
B=np.array([[1,2],[3,4]])
A+B

ValueError: operands could not be broadcast together with shapes (3,1) (2,2) 

In [ ]:
H,W=3,3
rgb_image = np.random.randint(0, 256, size=(H, W, 3), dtype=np.uint8)

color_fix=[10,20,30]
fixed_image=rgb_image+color_fix
print(rgb_image)
fixed_image

[[[177 111  77]
  [245  44  12]
  [ 52 179  70]]

 [[242  14  80]
  [ 36 191  39]
  [152  53 250]]

 [[156 221 186]
  [146 144  65]
  [ 21  26  91]]]


array([[[187, 131, 107],
        [255,  64,  42],
        [ 62, 199, 100]],

       [[252,  34, 110],
        [ 46, 211,  69],
        [162,  73, 280]],

       [[166, 241, 216],
        [156, 164,  95],
        [ 31,  46, 121]]])

In [59]:
import numpy as np
rng=np.random.default_rng(0)
rndX=rng.integers(10, size=(10,10))
rndX

array([[8, 6, 5, 2, 3, 0, 0, 0, 1, 8],
       [6, 9, 5, 6, 9, 7, 6, 5, 5, 9],
       [2, 8, 6, 0, 3, 8, 5, 0, 7, 7],
       [8, 1, 0, 8, 0, 5, 0, 2, 4, 4],
       [4, 0, 0, 1, 0, 6, 5, 6, 2, 6],
       [7, 3, 4, 9, 8, 9, 3, 6, 9, 6],
       [8, 6, 7, 3, 8, 1, 5, 7, 8, 5],
       [3, 3, 4, 4, 7, 8, 0, 9, 5, 3],
       [6, 5, 2, 3, 7, 5, 5, 3, 7, 3],
       [3, 8, 2, 2, 7, 6, 0, 0, 3, 8]])

In [60]:

avg_X=rndX.mean(axis=1)
avg_X

array([3.3, 6.7, 4.6, 3.2, 3. , 6.4, 5.8, 4.6, 4.6, 3.9])

In [61]:
mean_X=rndX-avg_X

In [62]:
norm_X=np.linalg.norm(mean_X,ord=2,axis=0)
norm_X

array([ 9.84377976, 10.83051245,  8.03741252,  9.1214034 , 12.32882801,
        9.3059121 , 12.04159458, 10.09950494,  8.08702665,  8.99444273])

In [64]:
np.set_printoptions(2)

X_normalized=(avg_X-mean_X)/norm_X
X_normalized

array([[-0.14,  0.68,  0.52,  0.48,  0.24,  1.38,  0.96,  0.91,  1.01,
        -0.02],
       [ 0.06,  0.41,  0.52,  0.04, -0.24,  0.62,  0.47,  0.42,  0.52,
        -0.13],
       [ 0.47,  0.5 ,  0.4 ,  0.7 ,  0.24,  0.52,  0.55,  0.91,  0.27,
         0.09],
       [-0.14,  1.14,  1.14, -0.18,  0.49,  0.84,  0.96,  0.71,  0.64,
         0.42],
       [ 0.26,  1.24,  1.14,  0.59,  0.49,  0.73,  0.55,  0.32,  0.89,
         0.2 ],
       [-0.04,  0.96,  0.65, -0.29, -0.16,  0.41,  0.71,  0.32,  0.02,
         0.2 ],
       [-0.14,  0.68,  0.27,  0.37, -0.16,  1.27,  0.55,  0.22,  0.15,
         0.31],
       [ 0.37,  0.96,  0.65,  0.26, -0.08,  0.52,  0.96,  0.02,  0.52,
         0.53],
       [ 0.06,  0.78,  0.9 ,  0.37, -0.08,  0.84,  0.55,  0.61,  0.27,
         0.53],
       [ 0.37,  0.5 ,  0.9 ,  0.48, -0.08,  0.73,  0.96,  0.91,  0.77,
        -0.02]])

### np.multiply.outer で外積行列。

In [72]:
rng=np.random.default_rng(0)
X=rng.integers(10,size=(3,1))
Y=rng.integers(10,size=(1,3))
print(X)
print(Y)
print(X*Y)
np.multiply.outer(X,Y)




[[8]
 [6]
 [5]]
[[2 3 0]]
[[16 24  0]
 [12 18  0]
 [10 15  0]]


array([[[[16, 24,  0]]],


       [[[12, 18,  0]]],


       [[[10, 15,  0]]]])

In [73]:
X=rng.integers(10,size=(3,3))
print(X)
3*X

[[0 0 1]
 [8 6 9]
 [5 6 9]]


array([[ 0,  0,  3],
       [24, 18, 27],
       [15, 18, 27]])

In [78]:
A=np.random.randint(0,10,1000)
np.count_nonzero(A>2)


np.int64(701)

In [85]:
A=np.random.randint(0,1000,1000)
B=np.random.randint(0,1000,1000)
np.sum(np.isin(A,B))

np.int64(641)

In [91]:

A[[i for i in range(0,len(A),10)]]

array([147, 764, 516, 372,  72, 241, 764, 220, 138, 658, 487, 302, 228,
       451, 219, 635, 805, 668,  11, 157, 905, 790, 646, 542, 421, 417,
       631, 143, 140,  20, 753, 327, 461, 236, 922, 363, 219, 752, 472,
       244, 403, 606, 278, 451, 549,  98, 932, 960,   2, 540, 551,  76,
       969, 793, 962, 221, 346, 547, 334, 346, 999, 235,  72, 560, 628,
       275, 270, 144, 920, 513, 112, 567, 169, 978, 911, 869, 215, 817,
       806,  32, 253, 601, 372, 520,  14, 632, 554, 140, 811, 329, 938,
       579,   5, 871, 502, 645, 760, 410,  76,  69], dtype=int32)

In [ ]:
A=[10]
