Jupyter Notebook を起動し、新しいノートブックを作成せよ。

In [54]:
import numpy as np

1 行のセルに print("Hello, Data Science!") を書いて実行。

In [55]:
print("Hello, Data Science!")

Hello, Data Science!


Markdown セルを追加し、# 私の最初のノート と見出しを書く。

len? を実行してヘルプを表示。

In [56]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

np.mean?? でソースコードを確認。

In [57]:
np.mean??

Signature:      
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.mean(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function mean at 0x000001BD671CC860>
File:            e:\python\python-data-science-handbook\venv\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_mean_dispatcher)
def mean(a, axis=None, dtype=None, out=None, keepdims=np._NoValue, *,
         where=np._NoValue):
    """
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : 

Tab 補完で numpy.random.default_rng を補完。

In [58]:
np.random.default_rng

<cyfunction default_rng at 0x000001BD7D45CDC0>

%lsmagic で Magic コマンド一覧を表示。

In [59]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %code_wrap  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %mamba  %matplotlib  %micromamba  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %uv  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%code_wrap  %%debug  %%file  %%html  %%javascript  %%js  %%l

%timeit sum(range(1_000)) を計測。

In [60]:
%timeit sum(range(1_000))

26.7 μs ± 5.03 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


%run hello.py で自作スクリプトを実行。

In [61]:
%run hello.py 

Hello world.


%prun で自作関数のプロファイルを取得。

In [62]:
def sample_func_1():
    index_list = []
    for i in range(1000000):
        index_list.append(i)


def sample_func_2():
    index_list = []
    for i in range(2000000):
        index_list.append(i)


def sample_func_3():
    index_list = []
    for i in range(6000000):
        index_list.append(i)


def sample_func_4():
    sample_func_1()
    sample_func_2()
    sample_func_3()


In [63]:
%%prun
sample_func_4()

         9000264 function calls (9000260 primitive calls) in 5.804 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  9000000    2.679    0.000    2.679    0.000 {method 'append' of 'list' objects}
        1    1.899    1.899    3.637    3.637 2123655570.py:13(sample_func_3)
        1    0.661    0.661    1.249    1.249 2123655570.py:7(sample_func_2)
        1    0.291    0.291    0.573    0.573 2123655570.py:1(sample_func_1)
        1    0.211    0.211    5.670    5.670 2123655570.py:19(sample_func_4)
        2    0.036    0.018    0.066    0.033 {built-in method select.select}
        2    0.025    0.012    0.046    0.023 socket.py:623(send)
        2    0.000    0.000    0.000    0.000 {method '__exit__' of 'sqlite3.Connection' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        3    0.000    0.000    0.000    0.000 attrsettr.py:66(_get_attr_opt)
        3    0.0

Python リスト [1,2,3] を作り type() を確認。

In [64]:
A=[1,2,3]
type(A)

list

同じ要素で np.array を作り型を比較。

In [65]:
B=np.array(A)
type(B)

numpy.ndarray

arr = np.arange(10) の shape, dtype, ndim を表示。

In [66]:
arr=np.arange(10)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,)
int64
1


14. `np.zeros((10,10))` を生成。


In [67]:
z=np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

arr.reshape(2,5) で形状変更。

In [68]:
arr_reshape=arr.reshape(2,5)
arr_reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

np.linspace(0,1,5) を生成。

In [69]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000001BD67223A60>
File:            e:\python\python-data-science-handbook\venv\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoin

In [70]:
B=np.linspace(0,1,5)
B

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

for ループで 1‒1e7 合計を計測。

In [71]:
%%timeit

c=0
for i in range(1,10**7+1):
    c+=i
c

824 ms ± 40.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


同じ計算を np.sum で行い速度比較。

In [72]:
%%timeit
npsum=np.sum(np.arange(1,10**7+1))
npsum

58.2 ms ± 2.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


dtype='float32' の乱数 100 万個を生成。

In [73]:
import random

In [74]:
%%timeit
for _ in range(1000000):
    random.random()

type(random.random())

110 ms ± 5.36 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


dtype='float32' の乱数 100 万個を生成。

In [75]:
np.random.rand(1000000).astype(np.float32)

array([0.63005894, 0.807874  , 0.94045293, ..., 0.6425384 , 0.21247151,
       0.10726532], shape=(1000000,), dtype=float32)

コピーとビューの挙動を確認。

In [76]:
# 元の配列
original_array = np.array([1, 2, 3, 4, 5])
print("元の配列:", original_array)

# コピーを作成
copied_array = original_array.copy()
print("コピーされた配列:", copied_array)

# コピーを変更
copied_array[0] = 99
print("コピーを変更後:", copied_array)
print("元の配列 (変化なし):", original_array)


元の配列: [1 2 3 4 5]
コピーされた配列: [1 2 3 4 5]
コピーを変更後: [99  2  3  4  5]
元の配列 (変化なし): [1 2 3 4 5]


In [77]:
zeroto99=np.arange(100)
zeroto99[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
random_matrix = np.random.rand(10, 10)
random_matrix

array([[0.05049423, 0.5949439 , 0.80833804, 0.45661858, 0.24905663,
        0.52318768, 0.40836922, 0.78370966, 0.05676933, 0.58152773],
       [0.47541216, 0.72143503, 0.04419478, 0.74588178, 0.2712309 ,
        0.00974726, 0.11024996, 0.78368817, 0.14384787, 0.92384605],
       [0.60676192, 0.55972371, 0.86989613, 0.93247547, 0.34970891,
        0.09989197, 0.494289  , 0.56309355, 0.02058699, 0.28428558],
       [0.05861863, 0.59922384, 0.77049597, 0.81109628, 0.40391647,
        0.94319568, 0.97610526, 0.91143138, 0.00246639, 0.92963163],
       [0.33771186, 0.32283734, 0.67718371, 0.05298596, 0.69871127,
        0.18687927, 0.74888247, 0.0094489 , 0.8779821 , 0.05377911],
       [0.17508651, 0.34174062, 0.68724171, 0.32696176, 0.07523469,
        0.75789797, 0.49585577, 0.83320127, 0.7926772 , 0.93614794],
       [0.62514192, 0.49413563, 0.5327439 , 0.71079472, 0.16744429,
        0.33584731, 0.72500401, 0.87773502, 0.94704749, 0.26662397],
       [0.47599285, 0.92070417, 0.3471905

10×10 配列の 1 行目を取得。

In [79]:
random_matrix[0]

array([0.05049423, 0.5949439 , 0.80833804, 0.45661858, 0.24905663,
       0.52318768, 0.40836922, 0.78370966, 0.05676933, 0.58152773])

同配列の 1 列目を取得。

In [80]:
random_matrix[:,0]

array([0.05049423, 0.47541216, 0.60676192, 0.05861863, 0.33771186,
       0.17508651, 0.62514192, 0.47599285, 0.99100691, 0.67928394])

3×3 のサブ配列をスライス取得。

In [81]:
random_matrix[:3,:3]

array([[0.05049423, 0.5949439 , 0.80833804],
       [0.47541216, 0.72143503, 0.04419478],
       [0.60676192, 0.55972371, 0.86989613]])

ビューを変更して元配列も変わることを確認。

In [82]:
c=random_matrix
c[0,0]=0
random_matrix[0]

array([0.        , 0.5949439 , 0.80833804, 0.45661858, 0.24905663,
       0.52318768, 0.40836922, 0.78370966, 0.05676933, 0.58152773])

(2,3) 要素を書き換え。

In [83]:
c[2,2]=0
c[:3,:3]

array([[0.        , 0.5949439 , 0.80833804],
       [0.47541216, 0.72143503, 0.04419478],
       [0.60676192, 0.55972371, 0.        ]])

arr[::-1] で逆順。

In [84]:
original=np.array([
     [1,2,3,4,5,6,7,8,9,10],
     [11,12,13,14,15,16,17,18,19,20],
     [21,22,23,24,25,26,27,28,29,30],
     [31,32,33,34,35,36,37,38,39,40]
     ])

In [85]:
arr=original.copy()

In [86]:
arr[::-1]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

arr[:,::2] で偶数列抽出。

In [87]:

arr[:,::2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

3 の倍数だけ抽出。

In [88]:
arr[arr%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

奇数を ‑1 に置換。

In [89]:
arr[arr%2!=0]=-1
arr

array([[-1,  2, -1,  4, -1,  6, -1,  8, -1, 10],
       [-1, 12, -1, 14, -1, 16, -1, 18, -1, 20],
       [-1, 22, -1, 24, -1, 26, -1, 28, -1, 30],
       [-1, 32, -1, 34, -1, 36, -1, 38, -1, 40]])

In [90]:
original

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

np.square(arr) を計算。

In [91]:
np.square(original)

array([[   1,    4,    9,   16,   25,   36,   49,   64,   81,  100],
       [ 121,  144,  169,  196,  225,  256,  289,  324,  361,  400],
       [ 441,  484,  529,  576,  625,  676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600]])

np.sin, np.cos, np.tan を一括計算。

In [92]:
theta=np.pi*(45/180)
theta
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

0.7071067811865476
0.7071067811865476
0.9999999999999999


np.square(arr) を計算。

In [93]:
np.exp(arr)

array([[3.67879441e-01, 7.38905610e+00, 3.67879441e-01, 5.45981500e+01,
        3.67879441e-01, 4.03428793e+02, 3.67879441e-01, 2.98095799e+03,
        3.67879441e-01, 2.20264658e+04],
       [3.67879441e-01, 1.62754791e+05, 3.67879441e-01, 1.20260428e+06,
        3.67879441e-01, 8.88611052e+06, 3.67879441e-01, 6.56599691e+07,
        3.67879441e-01, 4.85165195e+08],
       [3.67879441e-01, 3.58491285e+09, 3.67879441e-01, 2.64891221e+10,
        3.67879441e-01, 1.95729609e+11, 3.67879441e-01, 1.44625706e+12,
        3.67879441e-01, 1.06864746e+13],
       [3.67879441e-01, 7.89629602e+13, 3.67879441e-01, 5.83461743e+14,
        3.67879441e-01, 4.31123155e+15, 3.67879441e-01, 3.18559318e+16,
        3.67879441e-01, 2.35385267e+17]])

乱数 100 万個の平均を計算。

In [94]:
n=1000000
a=np.random.rand(n)

In [95]:
a.sum()/n

np.float64(0.5005894250444608)

最大値と最小値の差を求める。

In [96]:
min_a=min(a)
max_a=max(a)
max_a-min_a

np.float64(0.9999989222732081)

 次元配列で axis=0 合計。

In [97]:
sum_axis_0 = np.sum(original, axis=0)
sum_axis_0

array([ 64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

np.percentile で 25/50/75 % 点。

In [98]:
for i in [0,25,50,75,100]:
    print(np.percentile(original,i))

1.0
10.75
20.5
30.25
40.0


argsort で昇順インデックス。

In [99]:
np.argsort(original)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

partition で上位 5 要素抽出。

In [100]:
p=np.partition(sum_axis_0,kth=5)
print(p)
p[:5]


[ 64  68  72  76  80  84  88  92  96 100]


array([64, 68, 72, 76, 80])

rng = np.random.default_rng(0) で再現可能に。

In [101]:
print("--- Run 1 ---")
rng1 = np.random.default_rng(0) # Seeded with 0
print("Random integers (rng1):", rng1.integers(10, size=5))
print("Random floats (rng1):", rng1.random(size=3))

print("\n--- Run 2 (Same Seed) ---")
rng2 = np.random.default_rng(0) # Seeded with 0 again
print("Random integers (rng2):", rng2.integers(10, size=5))
print("Random floats (rng2):", rng2.random(size=3))

--- Run 1 ---
Random integers (rng1): [8 6 5 2 3]
Random floats (rng1): [0.01652764 0.81327024 0.91275558]

--- Run 2 (Same Seed) ---
Random integers (rng2): [8 6 5 2 3]
Random floats (rng2): [0.01652764 0.81327024 0.91275558]


In [102]:
rng1 = np.random.default_rng(0)
random_matrix2 = rng1.integers(10, size=(5,5))
random_matrix2

array([[8, 6, 5, 2, 3],
       [0, 0, 0, 1, 8],
       [6, 9, 5, 6, 9],
       [7, 6, 5, 5, 9],
       [2, 8, 6, 0, 3]])

5×5 配列に [0,1,2,3,4] を足す。

In [103]:
random_matrix2+np.array([0,1,2,3,4])

array([[ 8,  7,  7,  5,  7],
       [ 0,  1,  2,  4, 12],
       [ 6, 10,  7,  9, 13],
       [ 7,  7,  7,  8, 13],
       [ 2,  9,  8,  3,  7]])

列方向に平均 0 のセンタリング。

In [104]:
column_means=random_matrix2.mean(axis=0)
centered=random_matrix2-column_means
centered

array([[ 3.4,  0.2,  0.8, -0.8, -3.4],
       [-4.6, -5.8, -4.2, -1.8,  1.6],
       [ 1.4,  3.2,  0.8,  3.2,  2.6],
       [ 2.4,  0.2,  0.8,  2.2,  2.6],
       [-2.6,  2.2,  1.8, -2.8, -3.4]])

In [105]:
centered.mean(axis=0)

array([ 3.55271368e-16,  1.77635684e-16, -1.77635684e-16,  1.77635684e-16,
       -3.55271368e-16])

メッシュグリッドで z = sin(x)+cos(y)。

In [106]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D # 3Dプロットに必要

# 1. x, yの範囲を定義
# -2π から 2π までを100分割した配列を生成
x = np.linspace(-2 * np.pi, 2 * np.pi, 100)
y = np.linspace(-2 * np.pi, 2 * np.pi, 100)

# 2. メッシュグリッドを生成
# xとyの1次元配列から、2次元の座標グリッドX, Yを生成
X, Y = np.meshgrid(x, y)

# 3. zの値を計算
# 各(X, Y)座標に対して Z = sin(X) + cos(Y) を計算
Z = np.sin(X) + np.cos(Y)

# 4. 3Dプロットの準備
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# 5. 3D曲面プロットを実行
# cmapでカラーマップを指定すると見やすくなる
surf = ax.plot_surface(X, Y, Z, cmap='viridis')

# 軸ラベルとタイトルの設定
ax.set_xlabel('x axis')
ax.set_ylabel('y axis')
ax.set_zlabel('z axis')
ax.set_title('z = sin(x) + cos(y)')

# カラーバーを追加
fig.colorbar(surf, shrink=0.5, aspect=10)

# グラフを表示
plt.show()


ModuleNotFoundError: No module named 'matplotlib'

ブロードキャストで距離行列を生成。

In [ ]:
np.newaxis?

Type:        NoneType
String form: None
Docstring:   The type of the None singleton.

In [ ]:
X = np.array([[0, 0], [1, 2], [3, 3], [5, 2], [3, 0]])
sum_sq = np.sum(X**2, axis=1)
dist_sq = sum_sq[:, np.newaxis] + sum_sq[np.newaxis, :] - 2 * (X @ X.T)
dist_sq_clipped = np.maximum(dist_sq, 0)
dist_matrix_fast = np.sqrt(dist_sq_clipped)
print("方法2で生成した距離行列:")
print(dist_matrix_fast)

方法2で生成した距離行列:
[[0.         2.23606798 4.24264069 5.38516481 3.        ]
 [2.23606798 0.         2.23606798 4.         2.82842712]
 [4.24264069 2.23606798 0.         2.23606798 3.        ]
 [5.38516481 4.         2.23606798 0.         2.82842712]
 [3.         2.82842712 3.         2.82842712 0.        ]]


In [ ]:
A=np.array([[1],[2],[3]])
B=np.array([[1,2,3,4]])
A+B

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [ ]:
A=np.array([[1],[2],[3]])
B=np.array([[1,2],[3,4]])
A+B

ValueError: operands could not be broadcast together with shapes (3,1) (2,2) 

In [ ]:
H,W=3,3
rgb_image = np.random.randint(0, 256, size=(H, W, 3), dtype=np.uint8)

color_fix=[10,20,30]
fixed_image=rgb_image+color_fix
print(rgb_image)
fixed_image

[[[177 111  77]
  [245  44  12]
  [ 52 179  70]]

 [[242  14  80]
  [ 36 191  39]
  [152  53 250]]

 [[156 221 186]
  [146 144  65]
  [ 21  26  91]]]


array([[[187, 131, 107],
        [255,  64,  42],
        [ 62, 199, 100]],

       [[252,  34, 110],
        [ 46, 211,  69],
        [162,  73, 280]],

       [[166, 241, 216],
        [156, 164,  95],
        [ 31,  46, 121]]])

In [ ]:
import numpy as np
rng=np.random.default_rng(0)
rndX=rng.integers(10, size=(10,10))
rndX

array([[8, 6, 5, 2, 3, 0, 0, 0, 1, 8],
       [6, 9, 5, 6, 9, 7, 6, 5, 5, 9],
       [2, 8, 6, 0, 3, 8, 5, 0, 7, 7],
       [8, 1, 0, 8, 0, 5, 0, 2, 4, 4],
       [4, 0, 0, 1, 0, 6, 5, 6, 2, 6],
       [7, 3, 4, 9, 8, 9, 3, 6, 9, 6],
       [8, 6, 7, 3, 8, 1, 5, 7, 8, 5],
       [3, 3, 4, 4, 7, 8, 0, 9, 5, 3],
       [6, 5, 2, 3, 7, 5, 5, 3, 7, 3],
       [3, 8, 2, 2, 7, 6, 0, 0, 3, 8]])

In [ ]:

avg_X=rndX.mean(axis=1)
avg_X

array([3.3, 6.7, 4.6, 3.2, 3. , 6.4, 5.8, 4.6, 4.6, 3.9])

In [ ]:
mean_X=rndX-avg_X

In [ ]:
norm_X=np.linalg.norm(mean_X,ord=2,axis=0)
norm_X

array([ 9.84377976, 10.83051245,  8.03741252,  9.1214034 , 12.32882801,
        9.3059121 , 12.04159458, 10.09950494,  8.08702665,  8.99444273])

In [ ]:
np.set_printoptions(2)

X_normalized=(avg_X-mean_X)/norm_X
X_normalized

array([[-0.14,  0.68,  0.52,  0.48,  0.24,  1.38,  0.96,  0.91,  1.01,
        -0.02],
       [ 0.06,  0.41,  0.52,  0.04, -0.24,  0.62,  0.47,  0.42,  0.52,
        -0.13],
       [ 0.47,  0.5 ,  0.4 ,  0.7 ,  0.24,  0.52,  0.55,  0.91,  0.27,
         0.09],
       [-0.14,  1.14,  1.14, -0.18,  0.49,  0.84,  0.96,  0.71,  0.64,
         0.42],
       [ 0.26,  1.24,  1.14,  0.59,  0.49,  0.73,  0.55,  0.32,  0.89,
         0.2 ],
       [-0.04,  0.96,  0.65, -0.29, -0.16,  0.41,  0.71,  0.32,  0.02,
         0.2 ],
       [-0.14,  0.68,  0.27,  0.37, -0.16,  1.27,  0.55,  0.22,  0.15,
         0.31],
       [ 0.37,  0.96,  0.65,  0.26, -0.08,  0.52,  0.96,  0.02,  0.52,
         0.53],
       [ 0.06,  0.78,  0.9 ,  0.37, -0.08,  0.84,  0.55,  0.61,  0.27,
         0.53],
       [ 0.37,  0.5 ,  0.9 ,  0.48, -0.08,  0.73,  0.96,  0.91,  0.77,
        -0.02]])

### np.multiply.outer で外積行列。

In [ ]:
rng=np.random.default_rng(0)
X=rng.integers(10,size=(3,1))
Y=rng.integers(10,size=(1,3))
print(X)
print(Y)
print(X*Y)
np.multiply.outer(X,Y)




[[8]
 [6]
 [5]]
[[2 3 0]]
[[16 24  0]
 [12 18  0]
 [10 15  0]]


array([[[[16, 24,  0]]],


       [[[12, 18,  0]]],


       [[[10, 15,  0]]]])

In [ ]:
X=rng.integers(10,size=(3,3))
print(X)
3*X

[[0 0 1]
 [8 6 9]
 [5 6 9]]


array([[ 0,  0,  3],
       [24, 18, 27],
       [15, 18, 27]])

In [ ]:
A=np.random.randint(0,10,1000)
np.count_nonzero(A>2)


np.int64(701)

In [3]:
import numpy as np

In [4]:
A=np.random.randint(0,1000,1000)
B=np.random.randint(0,1000,1000)
np.sum(np.isin(A,B))

np.int64(651)

In [7]:

print(A[[i for i in range(0,len(A),2)]][:10])
A[::2][:10]

[568 368 966 817 276 549 594 483 731 738]


array([568, 368, 966, 817, 276, 549, 594, 483, 731, 738], dtype=int32)

In [18]:
A=np.array([10,np.nan,20,np.nan,10])
print(A)
np.nanmean(A)



[10. nan 20. nan 10.]


np.float64(13.333333333333334)

In [52]:
rng=np.random.default_rng(0)
a=rng.integers(-10,10,10)
print(a)
np.where(a>0,a*-1,a*-1)

[  7   2   0  -5  -4 -10  -9 -10  -7   6]


array([-7, -2,  0,  5,  4, 10,  9, 10,  7, -6])

In [58]:
b=rng.integers(1,10,10)
print(b)
np.unique(b)

[8 2 1 8 1 5 1 3 5 4]


array([1, 2, 3, 4, 5, 8])

In [59]:
print(a)
print(b)
np.isin(a,b)

[  7   2   0  -5  -4 -10  -9 -10  -7   6]
[8 2 1 8 1 5 1 3 5 4]


array([False,  True, False, False, False, False, False, False, False,
       False])

In [64]:
A = np.array([[0,1,2],[2,1,0]])
choices = [[7], [0], [1]]     # shape (3,1) だが列方向にブロードキャスト可
np.choose(A, choices)         # → array([[7,0,1],[1,0,7]])


array([[7, 0, 1],
       [1, 0, 7]])